"""Declarative base, column helpers and mixins.

``TenantOwnedMixin`` is the structural half of the tenant isolation guarantee
(spec 6, 7): a tenant-owned table cannot be declared without ``tenant_id``.
The enforcement half lives in the repository layer (Phase 3).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, MetaData, String, Text, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from shared.models import StrEnum, SyncStatus

# Explicit constraint naming so Alembic autogenerate produces stable,
# reversible migrations instead of database-assigned names.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def enum_column(enum_cls: type[StrEnum], **kwargs: Any) -> Mapped[Any]:
    """A column storing an enum as VARCHAR with a CHECK constraint.

    Deliberately not a native PostgreSQL ENUM. Adding a value to a native enum
    requires ALTER TYPE, which cannot run inside a transaction alongside the
    rest of a migration on older servers and cannot be rolled back cleanly.
    A CHECK constraint is just a constraint swap, so schema evolution stays
    reversible — which CI enforces by running every migration back down to
    base.
    """
    return mapped_column(
        SAEnum(enum_cls, native_enum=False, validate_strings=True, length=64),
        **kwargs,
    )


def json_column(**kwargs: Any) -> Mapped[Any]:
    """A JSONB column. JSONB rather than JSON so it can be indexed and queried."""
    return mapped_column(postgresql.JSONB, **kwargs)


class UUIDPrimaryKeyMixin:
    """UUID primary key generated application-side.

    Generated by the application rather than the database so a call's
    identifiers exist before any row is written — the worker needs a
    ``call_id`` to log against from the first event (spec 43).
    """

    id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class TenantOwnedMixin:
    """Marks a table as tenant-owned (spec 6).

    Every tenant-owned object carries ``tenant_id``. The cascade means a
    removed tenant leaves nothing behind that another tenant could reach.
    """

    @property
    def _tenant_fk(self) -> str:  # pragma: no cover - documentation only
        return "tenants.id"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


class LiveKitSyncMixin:
    """Mirrors a LiveKit resource and tracks whether the two agree.

    PostgreSQL is the configuration source of truth (spec 10, 79); LiveKit
    holds the live resource. Storing the LiveKit ID here is what makes
    reconciliation and drift detection possible (spec 12, 46) — without it,
    the only way to find an orphaned LiveKit resource is to guess by name.
    """

    #: Identifier returned by the LiveKit API. Null until the first successful
    #: create, which is also how a never-synced row is distinguished from a
    #: drifted one.
    livekit_resource_id: Mapped[str | None] = mapped_column(String(255), index=True)

    sync_status: Mapped[SyncStatus] = enum_column(
        SyncStatus, nullable=False, default=SyncStatus.PENDING
    )
    last_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    #: Last failure detail, surfaced in the LiveKit admin section so an
    #: operator can act on it rather than reading application logs.
    sync_error: Mapped[str | None] = mapped_column(Text)

    #: Number of consecutive failed attempts, so Retry can back off instead of
    #: hammering the LiveKit admin API.
    sync_attempts: Mapped[int] = mapped_column(nullable=False, default=0)
