"""provider requires_credential

Revision ID: b46727df64e0
Revises: 5a724fc76c9f
Create Date: 2026-09-11 06:34:59.474387+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b46727df64e0'
down_revision: str | None = '5a724fc76c9f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('requires_credential', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'requires_credential')
    # ### end Alembic commands ###
